Add translations support
tclaus/stocks pull request #30
Opened 2023-08-01 11:56 UTC by hfsfox

2023-08-01 13:34 UTC, tclaus requested changes
Thanks for your contribution. I will enable translations for this next. 
But I have some issues found. 
Can you also fix the conflicts by merging latest develop?

2023-08-01 15:47 UTC, hfsfox commented on source/gui/chartView/ChartTimeRangeBar.cpp
> +        BView(BRect(), B_TRANSLATE("chartTimeRangeBar"), B_FOLLOW_ALL, B_WILL_DRAW) {
Oh, it'smy mistake, not it all needed, only with visible text, sorry

At the moment I dont know how to add .catkeys files with locale support to CMake but in generic Makefiles it possible in following way: add app signature and than "make catkeys" and get en.catkeys and it need to be edited with CatkeysEditor and saved to another file with locale name *.catkyes and than "collectcatkeys -o locales/uk.catkeys -l ukrainian -s application/x-vnd.Haiku-App objects.x86_64-cc11-release/App.pre" and "make bindcatalogs" and link with binary

2023-08-01 15:52 UTC, hfsfox commented on source/gui/chartView/ChartTimeRangeBar.cpp
> +            .Add(createButton(B_TRANSLATE("5 Y"), new BMessage(TimeRange::M_FIVE_YEARS)));
It make sense in cyrillic or another languages for exmple, because in my opinion without localization of dates its looks llike quite partially translated

2023-08-01 16:00 UTC, hfsfox commented on source/gui/MainWindow.cpp
> +                  B_ASYNCHRONOUS_CONTROLS | B_AUTO_UPDATE_SIZE_LIMITS),
Thats flag allow to set minimal width and height and allow to zoom window but not smaller than setted for window rect, and I think its really samll change for separate PR

2023-08-05 17:44 UTC, tclaus commented on source/gui/MainWindow.cpp
> +                  B_ASYNCHRONOUS_CONTROLS | B_AUTO_UPDATE_SIZE_LIMITS),
I checked this flag and I don't like the behavior - the Windows won't get bigger. There is just a lower limit, not a max limit. Can you check this again?

2023-08-06 20:30 UTC, closed without merging